name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: "ubuntu:devel"
    
    steps:
      - uses: actions/checkout@v3

      - name: run scripts
        run: |
          apt-get update && apt-get install curl
          echo "TEST=" | tee -a $GITHUB_ENV
          export AAA=$(curl -s https://xanmod.org/ | grep -A1 MAIN | grep -E '[0-9]+\.[0-9]+' -o | head -n1)
          echo $AAA

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        if: ${{ env.TEST }}
        with:
          body: test?
          tag_name: v0.0.1
          files: README.md
          generate_release_notes: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
