name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: "ubuntu:devel"
    
    steps:
      - uses: actions/checkout@main

      - name: install anything
        run: |
          apt-get update && apt-get install -y curl bash

      - name: run scripts
        shell: bash
        run: |
          git clone https://github.com/Locietta/github-action-playground.git
          # test if now we can run git without safe directory thing...
          
      # - name: GH Release
      #   uses: softprops/action-gh-release@v0.1.14
      #   if: ${{ env.TEST }}
      #   with:
      #     body: test?
      #     tag_name: v0.0.1
      #     files: README.md
      #     generate_release_notes: true
      #     token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
