name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: "ubuntu:20.04"
    
    steps:
      - name: Trust My Directory
        run: git config --global --add safe.directory /__w/github-action-playground/github-action-playground
      - uses: actions/checkout@v3

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          body: test?
          tag_name: v0.0.1
          files: README.md
          generate_release_notes: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
